const templates = [
  {
    name: "Template 1",
    picture: "template_001.jpeg",
    element: [
      {
        type: "background",
        filePath: "template_001_edit.jpeg",
      },
      {
        type: "text",
        text: "이것은 템플릿의 제목입니다",
        fontFamily: "'Black Han Sans', sans-serif;",
        fontSize: 40,
        fontFamily: "",
        location: {
          x: 24,
          y: 36,
        },
        zIndex: 200,
        color: "#43784c",
      },
      {
        type: "text",
        text: "Work Experience",
        fontFamily: "'Black Han Sans', sans-serif;",
        fontSize: 30,
        fontFamily: "",
        location: {
          x: 32,
          y: 76,
        },
        zIndex: 200,
        color: "#43784c",
      },
      {
        type: "text",
        text: "이것은 중간에 인용구입니다",
        fontFamily: "'Black Han Sans', sans-serif;",
        fontSize: 36,
        fontFamily: "",
        location: {
          x: 100,
          y: 130,
        },
        zIndex: 200,
        color: "#43784c",
      },
      {
        type: "text",
        text: "교육 연습",
        fontFamily: "'Black Han Sans', sans-serif;",
        fontSize: 38,
        fontFamily: "",
        location: {
          x: 55,
          y: 305,
        },
        zIndex: 200,
        color: "#FFFFFF",
      },
      {
        type: "text",
        text: "Teaching Practice",
        fontFamily: "'Black Han Sans', sans-serif;",
        fontSize: 18,
        fontFamily: "",
        location: {
          x: 55,
          y: 350,
        },
        zIndex: 200,
        color: "#FFFFFF",
      },
      {
        type: "text",
        text: "교육 실습 설명",
        fontFamily: "'Black Han Sans', sans-serif;",
        fontSize: 24,
        fontFamily: "",
        location: {
          x: 230,
          y: 306,
        },
        zIndex: 200,
        color: "#1d291d",
      },
      {
        type: "text",
        text: "관측",
        fontFamily: "'Black Han Sans', sans-serif;",
        fontSize: 38,
        fontFamily: "",
        location: {
          x: 55,
          y: 395,
        },
        zIndex: 200,
        color: "#FFFFFF",
      },
      {
        type: "text",
        text: "Observation",
        fontFamily: "'Black Han Sans', sans-serif;",
        fontSize: 18,
        fontFamily: "",
        location: {
          x: 55,
          y: 440,
        },
        zIndex: 200,
        color: "#FFFFFF",
      },
      {
        type: "text",
        text: "관찰에 대한 설명입니다.",
        fontFamily: "'Black Han Sans', sans-serif;",
        fontSize: 24,
        fontFamily: "",
        location: {
          x: 230,
          y: 396,
        },
        zIndex: 200,
        color: "#1d291d",
      },
      {
        type: "text",
        text: "자기 숙달",
        fontFamily: "'Black Han Sans', sans-serif;",
        fontSize: 38,
        fontFamily: "",
        location: {
          x: 55,
          y: 480,
        },
        zIndex: 200,
        color: "#FFFFFF",
      },
      {
        type: "text",
        text: "Self-Mastery",
        fontFamily: "'Black Han Sans', sans-serif;",
        fontSize: 18,
        fontFamily: "",
        location: {
          x: 55,
          y: 525,
        },
        zIndex: 200,
        color: "#FFFFFF",
      },
      {
        type: "text",
        text: "이것은 자기 숙달을위한 텍스트입니다.",
        fontFamily: "'Black Han Sans', sans-serif;",
        fontSize: 24,
        fontFamily: "",
        location: {
          x: 230,
          y: 486,
        },
        zIndex: 200,
        color: "#1d291d",
      },
    ],
  },
  {
    name: "Template 2",
    picture: "template_002.jpeg",
  },
  {
    name: "Template 3",
    picture: "template_003.jpeg",
  },
  {
    name: "Template 4",
    picture: "template_004.jpeg",
  },
  {
    name: "Template 5",
    picture: "template_005.jpeg",
  },
  {
    name: "Template 6",
    picture: "template_006.jpeg",
  },
  {
    name: "Template 7",
    picture: "template_007.jpeg",
  },
  {
    name: "Template 8",
    picture: "template_008.jpeg",
  },
  {
    name: "Template 9",
    picture: "template_009.jpeg",
  },
  {
    name: "Template 10",
    picture: "template_010.jpeg",
  },
  {
    name: "Template 11",
    picture: "template_011.jpeg",
  },
];

export default templates;
